import os
import logging
import urllib.parse
from datetime import datetime

logger = logging.getLogger(__name__)


def generate_mailto_link(lead_data: dict) -> str:
    """Generate a mailto link for client-side email submission."""
    to_email = os.getenv("LEAD_TO_EMAIL", "futureai4all@gmail.com")
    subject = f"🚀 New Quote Lead: {lead_data.get('name')}"

    body = f"""
New Lead Capture Details:
-------------------------
Timestamp: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Name: {lead_data.get("name")}
Email: {lead_data.get("email")}
Phone: {lead_data.get("phone")}
Service: {lead_data.get("service")}
Best Time: {lead_data.get("best_time")}

Details/Goals:
{lead_data.get("details")}

-------------------------
Generated by PINNACLE AI Solutions MCP Chatbot
"""

    # URL encode the parameters
    params = {"subject": subject, "body": body}
    query_string = urllib.parse.urlencode(params)

    return f"mailto:{to_email}?{query_string}"


def send_lead_email(lead_data: dict) -> bool:
    """Deprecated: auto-sending requires SMTP setup. Returns False to trigger fallback."""
    logger.warning(
        "Auto-email attempted but SMTP is disabled in favor of mailto links."
    )
    return False


def check_email_config() -> bool:
    """Verify if email configuration is present."""
    return all(
        [
            os.getenv("SMTP_HOST"),
            os.getenv("SMTP_PORT"),
            os.getenv("SMTP_USER"),
            os.getenv("SMTP_PASS"),
        ]
    )
